---
- name: List files of /etc/logstash/conf.d/
  shell: >
    ls -1 /etc/logstash/conf.d/
  register: files

- name: Remove files except specified
  file:
    path: "/etc/logstash/conf.d/{{ item }}"
    state: absent
  with_items: "{{files.stdout_lines}}"
  when: item not in list_of_files_to_keep

- name: Create Logstash input configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-inputs.conf
  notify: restart logstash
  when: inputs is defined

- name: Create Logstash filters configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 02-filters.conf
  notify: restart logstash
  when: filters is defined

- name: Create Logstash outputs configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 03-outputs.conf
  notify: restart logstash
  when: outputs is defined
