---
- name: List files of /etc/logstash/conf.d/
  shell: >
    ls -1 /etc/logstash/conf.d/
  register: files

- name: Remove files except specified
  file:
    path: "/etc/logstash/conf.d/{{ item }}"
    state: absent
  with_items: "{{files.stdout_lines}}"
  when: item not in list_of_files_to_keep

- name: Copy Logstash configuration file.
  copy:
    src: "logstash.yml"
    dest: "/etc/logstash/logstash.yml"
    owner: root
    group: root
    mode: 0644

# Generate Avro Schema files based on variables passed through "logstash.avsc".
- name: Generate Avro Schema file.
  copy:
    content: "{{ item | to_nice_json }}"
    dest: "/etc/logstash/{{ item.name }}.avsc"
    owner: root
    group: root
    mode: 0644
  when: logstash.avsc is defined
  with_items: "{{ logstash.avsc }}"
  notify: restart logstash

- name: Create Logstash input configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-inputs.conf
  notify: restart logstash
  when: inputs is defined

- name: Create Logstash filters configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 02-filters.conf
  notify: restart logstash
  when: filters is defined

- name: Create Logstash outputs configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 03-outputs.conf
  notify: restart logstash
  when: outputs is defined
