---

- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- include: java.yml
  when: ls_java_install
  tags:
      - java

- name: Include OS Specific setup tasks
  include: setup-{{ ansible_os_family }}.yml

- include: config.yml
- include: ssl.yml
- include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
