---
- name: Get list of installed plugins.
  command: >
    ./bin/logstash-plugin list
    chdir=/usr/share/logstash
  register: logstash_plugins_list
  changed_when: false

- name: Install configured plugins.
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir=/usr/share/logstash
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash

- name: Install configured LOCAL plugins (you have to upload previously the file).
  command: >
    ./bin/logstash-plugin install file://{{ item.file }}
    chdir=/usr/share/logstash
  with_items: "{{ logstash_install_local_plugins }}"
  when: "item.name not in logstash_plugins_list.stdout"
  notify: restart logstash
