---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: http://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  template:
    src: logstash-repo.repo.j2
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: Install Logstash.
  yum: 
    pkg: "logstash-{{logstash_version}}"
    state: installed
